DROP DATABASE IF EXISTS stagium;
CREATE DATABASE IF NOT EXISTS stagium CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE stagium;

CREATE TABLE CAMPUS (
  id          INT UNSIGNED NOT NULL AUTO_INCREMENT,
  nom         VARCHAR(255) NOT NULL,
  numero      VARCHAR(8) NOT NULL,
  rue         VARCHAR(42) NOT NULL,
  complement  VARCHAR(42) NULL,
  code_postal CHAR(5) NOT NULL,
  ville       VARCHAR(100) NOT NULL,
  pays        VARCHAR(100) NOT NULL DEFAULT 'France',
  PRIMARY KEY (id)
);

CREATE TABLE CANDIDATURE (
  id               INT UNSIGNED NOT NULL AUTO_INCREMENT,
  date_candidature DATE NOT NULL,
  chemin_lm        VARCHAR(255) NOT NULL,
  chemin_cv        VARCHAR(255) NOT NULL,
  offre_id         INT UNSIGNED NOT NULL,
  utilisateur_id   INT UNSIGNED NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE COMPETENCE (
  id      INT UNSIGNED NOT NULL AUTO_INCREMENT,
  libelle VARCHAR(50) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE CONCERNE_ENTREPRISE (
  entreprise_id INT UNSIGNED NOT NULL,
  evaluation_id INT UNSIGNED NOT NULL,
  PRIMARY KEY   (entreprise_id, evaluation_id)
);

CREATE TABLE ENTREPRISE (
  id            INT UNSIGNED NOT NULL AUTO_INCREMENT,
  siren         CHAR(9) NOT NULL,
  nom           VARCHAR(255) NOT NULL,
  description   TEXT NULL,
  email         VARCHAR(255) NOT NULL,
  telephone     VARCHAR(20) NOT NULL,
  est_active    BOOLEAN NOT NULL DEFAULT 1,
  date_creation DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  secteur_id    INT UNSIGNED NULL,
  PRIMARY KEY (id)
);

CREATE TABLE ETUDIANT (
  utilisateur_id   INT UNSIGNED NOT NULL,
  statut_recherche ENUM('searching', 'placed', 'inactive') NOT NULL DEFAULT 'searching',
  PRIMARY KEY (utilisateur_id)
);

CREATE TABLE EVALUATION (
  id              INT UNSIGNED NOT NULL AUTO_INCREMENT,
  note            TINYINT UNSIGNED NOT NULL,
  commentaire     TEXT NULL,
  date_evaluation DATE NOT NULL,
  CONSTRAINT chk_note CHECK (note BETWEEN 1 AND 5),
  PRIMARY KEY (id)
);

CREATE TABLE FAVORI (
  offre_id        INT UNSIGNED NOT NULL,
  utilisateur_id  INT UNSIGNED NOT NULL,
  date_sauvegarde DATE,
  PRIMARY KEY (utilisateur_id, offre_id)
);

CREATE TABLE GERE (
  utilisateur_id INT UNSIGNED NOT NULL,
  promotion_id   INT UNSIGNED NOT NULL,
  PRIMARY KEY (utilisateur_id, promotion_id)
);

CREATE TABLE INSCRIT (
  utilisateur_id INT UNSIGNED NOT NULL,
  promotion_id   INT UNSIGNED NOT NULL,
  PRIMARY KEY (utilisateur_id, promotion_id)
);

CREATE TABLE OFFRE_STAGE (
  id               INT UNSIGNED NOT NULL AUTO_INCREMENT,
  titre            VARCHAR(200) NOT NULL,
  description      TEXT NULL,
  gratification    INT UNSIGNED NULL,
  date_debut       DATE NOT NULL,
  duree_semaines   TINYINT UNSIGNED NOT NULL,
  est_active       BOOLEAN NOT NULL DEFAULT 1,
  date_publication DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  site_entreprise_id INT UNSIGNED NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE PILOTE (
  utilisateur_id   INT UNSIGNED NOT NULL,
PRIMARY KEY (utilisateur_id)
);

CREATE TABLE ADMINISTRATEUR (
  utilisateur_id   INT UNSIGNED NOT NULL,
PRIMARY KEY (utilisateur_id)
);

CREATE TABLE PROMOTION (
  id             INT UNSIGNED NOT NULL AUTO_INCREMENT,
  type_cycle     VARCHAR(42) NOT NULL,
  annee_cycle    TINYINT UNSIGNED NOT NULL,
  filiere        VARCHAR(100) NOT NULL,
  annee_scolaire CHAR(9) NOT NULL,
  campus_id      INT UNSIGNED NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE REDIGE (
  utilisateur_id INT UNSIGNED NOT NULL,
  evaluation_id  INT UNSIGNED NOT NULL,
  PRIMARY KEY (utilisateur_id, evaluation_id)
);

CREATE TABLE REQUIERT (
  offre_id      INT UNSIGNED NOT NULL,
  competence_id INT UNSIGNED NOT NULL,
  PRIMARY KEY (offre_id, competence_id)
);

CREATE TABLE SECTEUR_ACTIVITE (
  id          INT UNSIGNED NOT NULL AUTO_INCREMENT,
  nom         VARCHAR(100) NOT NULL,
  description TEXT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE SITE_ENTREPRISE (
  id          INT UNSIGNED NOT NULL AUTO_INCREMENT,
  nom_site    VARCHAR(255) NOT NULL,
  siret       CHAR(14) NOT NULL,
  numero      VARCHAR(8) NOT NULL,
  rue         VARCHAR(42) NOT NULL,
  complement  VARCHAR(42) NULL,
  code_postal CHAR(5) NOT NULL,
  ville       VARCHAR(100) NOT NULL,
  pays        VARCHAR(100) NOT NULL DEFAULT 'France',
  entreprise_id INT UNSIGNED NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE UTILISATEUR (
  id            INT UNSIGNED NOT NULL AUTO_INCREMENT,
  email         VARCHAR(255) NOT NULL,
  mot_de_passe  VARCHAR(60) NOT NULL,
  prenom        VARCHAR(255) NOT NULL,
  nom           VARCHAR(255) NOT NULL,
  role          ENUM('etudiant', 'pilote', 'administrateur') NOT NULL,
  est_actif     BOOLEAN NOT NULL,
  date_creation DATE NOT NULL,
  PRIMARY KEY (id)
);

ALTER TABLE CANDIDATURE ADD FOREIGN KEY (utilisateur_id) REFERENCES ETUDIANT (utilisateur_id) ON DELETE CASCADE;
ALTER TABLE CANDIDATURE ADD FOREIGN KEY (offre_id) REFERENCES OFFRE_STAGE (id) ON DELETE CASCADE;

ALTER TABLE CONCERNE_ENTREPRISE ADD FOREIGN KEY (evaluation_id) REFERENCES EVALUATION (id) ON DELETE CASCADE;
ALTER TABLE CONCERNE_ENTREPRISE ADD FOREIGN KEY (entreprise_id) REFERENCES ENTREPRISE (id) ON DELETE CASCADE;

ALTER TABLE ENTREPRISE ADD FOREIGN KEY (secteur_id) REFERENCES SECTEUR_ACTIVITE (id) ON DELETE SET NULL;

ALTER TABLE FAVORI ADD FOREIGN KEY (offre_id) REFERENCES OFFRE_STAGE (id) ON DELETE CASCADE;
ALTER TABLE FAVORI ADD FOREIGN KEY (utilisateur_id) REFERENCES ETUDIANT (utilisateur_id) ON DELETE CASCADE;

ALTER TABLE GERE ADD FOREIGN KEY (promotion_id) REFERENCES PROMOTION (id) ON DELETE CASCADE;
ALTER TABLE GERE ADD FOREIGN KEY (utilisateur_id) REFERENCES PILOTE(utilisateur_id) ON DELETE CASCADE;

ALTER TABLE INSCRIT ADD FOREIGN KEY (promotion_id) REFERENCES PROMOTION (id) ON DELETE CASCADE;
ALTER TABLE INSCRIT ADD FOREIGN KEY (utilisateur_id) REFERENCES ETUDIANT (utilisateur_id) ON DELETE CASCADE;

ALTER TABLE OFFRE_STAGE ADD FOREIGN KEY (site_entreprise_id) REFERENCES SITE_ENTREPRISE (id) ON DELETE CASCADE;

ALTER TABLE PROMOTION ADD FOREIGN KEY (campus_id) REFERENCES CAMPUS (id) ON DELETE RESTRICT;

ALTER TABLE REDIGE ADD FOREIGN KEY (evaluation_id) REFERENCES EVALUATION (id) ON DELETE CASCADE;
ALTER TABLE REDIGE ADD FOREIGN KEY (utilisateur_id) REFERENCES UTILISATEUR (id) ON DELETE CASCADE;

ALTER TABLE REQUIERT ADD FOREIGN KEY (competence_id) REFERENCES COMPETENCE (id) ON DELETE CASCADE;
ALTER TABLE REQUIERT ADD FOREIGN KEY (offre_id) REFERENCES OFFRE_STAGE (id) ON DELETE CASCADE;

ALTER TABLE SITE_ENTREPRISE ADD FOREIGN KEY (entreprise_id) REFERENCES ENTREPRISE (id) ON DELETE CASCADE;

ALTER TABLE ETUDIANT ADD FOREIGN KEY (utilisateur_id) REFERENCES UTILISATEUR(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE PILOTE ADD FOREIGN KEY (utilisateur_id) REFERENCES UTILISATEUR(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE ADMINISTRATEUR ADD FOREIGN KEY (utilisateur_id) REFERENCES UTILISATEUR(id) ON DELETE CASCADE ON UPDATE CASCADE;
