Listen 443

<VirtualHost *:80>
    ServerName stagium.fr
    Redirect permanent / https://stagium.fr/
</VirtualHost>

<VirtualHost *:80>
    ServerName assets.stagium.fr
    Redirect permanent / https://assets.stagium.fr/
</VirtualHost>

<VirtualHost *:443>
    ServerName stagium.fr
    DocumentRoot "/srv/http/stagium/public"
    <Directory "/srv/http/stagium/public">
        Options FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>
    SSLEngine on
    SSLCertificateFile /etc/httpd/ssl/stagium.crt
    SSLCertificateKeyFile /etc/httpd/ssl/stagium.key
</VirtualHost>

<VirtualHost *:443>
    ServerName assets.stagium.fr
    DocumentRoot "/srv/http/stagium/static"
    <Directory "/srv/http/stagium/static">
        Options FollowSymLinks
        AllowOverride None
        Require all granted
    </Directory>
    SSLEngine on
    SSLCertificateFile /etc/httpd/ssl/stagium.crt
    SSLCertificateKeyFile /etc/httpd/ssl/stagium.key
</VirtualHost>